import type { Metadata } from "next";
import "./globals.css";
import { inter, cbyg } from "./fonts";
import { Providers } from "./providers";
import { UserProvider } from "@/context/UserContext";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="bg-black">
      <body className={`${inter.className} ${cbyg.variable} antialiased bg-black`}>
        <UserProvider><Providers>{children}</Providers></UserProvider>
      </body>
    </html>
  );
}
